### ISSUE TITLE
100ah battery stops replying after some time

### ISSUE THREAD

**Issue by cianpdx** [distancerunner/Renogy-Battery-ESP32-Bluetooth-MQTT-Bridge#1]
I copied your code and put on an ESP with an LCD for a battery meter in my van. works great for some time, then the battery stops replying. Nothing I can see is changing and it faults at a different number each time. Here are the debug logs from nimble with added counter - after that last writeValue() there is no reply.

Did you see this behavior at all? 

```c++
Counter: 83459
D NimBLERemoteCharacteristic: >> writeValue(), length: 8
D NimBLEClient: Got Client event 
D NimBLEClient: Notify Recieved for handle: 46
D NimBLEClient: checking service 0xfff0 for handle: 46
D NimBLEClient: Got Notification for characteristic Characteristic: uuid: 0xfff1, handle: 46 0x002e, props:  0x12
Descriptor: uuid: 0x2902, handle: 47
D NimBLEClient: Invoking callback for notification on characteristic Characteristic: uuid: 0xfff1, handle: 46 0x002e, props:  0x12
Descriptor: uuid: 0x2902, handle: 47
Counter: 83460
D NimBLERemoteCharacteristic: >> writeValue(), length: 8
D NimBLEClient: Got Client event 
D NimBLEClient: Notify Recieved for handle: 46
D NimBLEClient: checking service 0xfff0 for handle: 46
D NimBLEClient: Got Notification for characteristic Characteristic: uuid: 0xfff1, handle: 46 0x002e, props:  0x12
Descriptor: uuid: 0x2902, handle: 47
D NimBLEClient: Invoking callback for notification on characteristic Characteristic: uuid: 0xfff1, handle: 46 0x002e, props:  0x12
Descriptor: uuid: 0x2902, handle: 47
Counter: 83461
D NimBLERemoteCharacteristic: >> writeValue(), length: 8
``` 

I tried killing the BLE connection and restarting but that doesn't seem to be working. My plan right now is to just restart the ESP every hour...

**Comment by distancerunner** [comment]
Hey. It is great, that its working with your device to :). Yes, the code in the main repo has some troubles. I was debugging it in another branch and added some whatchdog features. Just try the other branch:
[add-dual-core-whatsdog-for-reset-in-case-of](https://github.com/distancerunner/VeDirectWiFiMQTToverWebSocket/tree/add-dual-core-whatsdog-for-reset-in-case-of)

This branch works fine since a few months (also while traveling around in regions with no phone reception). It has a timer, which is running all the time. A call of a domain and a proper 200 answer will reset this timer. If no reset occurs, the esp32 will restart by themself. Some times also the BLE connection runs in a time out, and the controller stand still. I was not able to find the reason.

Here you see, the reset is occurring some time (the long time slots), but the controller is able to keep themself working 24h a day:
![grafik](https://github.com/distancerunner/Renogy-Battery-ESP32-Bluetooth-MQTT-Bridge/assets/18682740/e7e7f0a7-62c8-4a10-baac-6d2b8cdbc6a4)

If this branch work properly with your esp32, I will merge it to the main branch. :)

**Comment by cianpdx** [comment]
ahh OK i will try with  BLEDevice::deinit(); on watchdog, and if that doesn't work i will use esp.restart() brute force

thanks

**Comment by distancerunner** [comment]
if you find a better solution, that would be great. I tried a lot with the BT lib, but was not able to remove all devices properly to reconnect completely new.

**Comment by cianpdx** [comment]
i think NimBLEDevice::deleteClient(pClient); is working good to clean state and reconnect normally. 

I will let it run overnight and see if any hangups

**Comment by cianpdx** [comment]
OK it has run for several days now without issue

 at 500ms request timer, if no response in 1000ms, kill the connection and restart

```c++
  if (millis() - last_read_time > read_timeout) {
    NimBLEDevice::deleteClient(pClient);
    connectToServer();
  }
```
